openapi: "3.1.0"
info:
  title: SailRaceSignalAPI
  contact:
    email: burszan@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0.0"
# TODO: set later...
#  servers:
#  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: user
    description: "User operations"
  - name: signal
    description: "Everything about the signal"
#------------------------------------------------------------------------------------------
paths:
#------------------------------------------------------------------------------------------
#        U S E R
#------------------------------------------------------------------------------------------
  /user{email}:
    post:
      tags: ["user"]
      summary: "Register/create a new user on the SailRaceSignal server"
      security: []   # No security
      parameters:
        - name: email
          in: path
          description: "E-mail of user to register"
          required: true
          schema:
            type: string
            format: email
      responses:
        '201':
          description: "Created"
          content:
            text/plain:
              schema:
                description: "User Id, e.g.: 12"
                type: integer
        '400':
          $ref: '#/components/responses/InvalidData'
        '409':
          $ref: '#/components/responses/AlreadyExists'
        '500':
          $ref: '#/components/responses/MailServerDown'
        '503':
          $ref: '#/components/responses/ServerBusy'
  /user/login:
    post:
      tags: ["user"]
      summary: "Login as registered user to the SailRaceSignal server"
      security: []   # No security
      requestBody:
        description: "Login info, which is email and password"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInfo'
        required: true
      responses:
        '200':
          description: "OK"
          content:
            text/plain:
              schema:
                description: "8721dab27ec8df21fa4ec31d997f2ac6, JWT Token, including the user id as primary key in the db"
                type: string
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '503':
          $ref: '#/components/responses/ServerBusy'
#------------------------------------------------------------------------------------------
#       S I G N A L
#------------------------------------------------------------------------------------------
  /signal:
    put:
      tags: ["signal"]
      summary: "Add signal info to server"
      requestBody:
        description: "Signal information"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Signal'
        required: true
      responses:
        '200':
          description: "Operation successfull"
        '400':
          $ref: '#/components/responses/InvalidData'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '409':
          $ref: '#/components/responses/AlreadyExists'
        '503':
          $ref: '#/components/responses/ServerBusy'
    get:
      tags: ["signal"]
      summary: "Get all signals info from the server"
      responses:
        '200':
          description: "Operation successfull"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  allOf:
                  - $ref: '#/components/schemas/SignalTime'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '503':
          $ref: '#/components/responses/ServerBusy'
  /signal{id}:
    delete:
      tags: ["signal"]
      summary: "Removes a signal from the database"
      parameters:
        - name: id
          in: path
          description: "Id of the signal"
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: "OK"
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '503':
          $ref: '#/components/responses/ServerBusy'
  /signal{filter}:
    get:
      tags: ["signal"]
      summary: "Get filtered signals from the server"
      parameters:
        - name: filter
          in: path
          description: "Filter signals to get"
          required: true
          schema:
            type: string
            format: text
      responses:
        '200':
          description: "Operation successfull"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  allOf:
                  - $ref: '#/components/schemas/SignalTime'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '503':
          $ref: '#/components/responses/ServerBusy'

#------------------------------------------------------------------------------------------
# COMPONENTS
#------------------------------------------------------------------------------------------
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
  schemas:
    LoginInfo:
      type: object
      description: "Login information sent to server"
      properties:
        email:
          type: string
          description: "helllo@world.com"
          example: "hello@world.com"
        password:
          type: string
          description: "the password"
    Signal:
      type: object
      description: "Signal time sent to server"
      properties:
        date_time:
          type: string
          description: "2025-03-15 19:00"
        five_min_serie:
          type: boolean
          description: "true or false"
          default: true
    SignalTime:
      type: object
      description: "Signals received from database"
      properties:
        id:
          type: integer
          description: "empty when addind or db-id when receiving"
          default: 0
        group_id:
          type: integer
          description: "empty when addind or group-id when receiving"
          default: 0
        date_time:
          type: string
          description: "The format must be yyyy-MM-dd hh:mm, e.g: 2025-03-15 19:00"
        signal_type:
          type: integer
          description: "Type of signal, (E.g.: one-minute signal, five min...)"
          default: 0
  responses:
    InvalidData:
      description: "400: Invalid data, missing something?"
      content:
        text/plain:
          schema:
                type: string
                format: text
                description: "Error message"
    UnauthorizedError:
      description: "401: Access token is missing or invalid"
      content:
        text/plain:
          schema:
                type: string
                format: text
                description: "Error message"
    AlreadyExists:
      description: "409: User already registered"
      content:
        text/plain:
          schema:
                type: string
                format: text
                description: "Error message"
    MailServerDown:
      description: "Mail service down"
      content:
        text/plain:
          schema:
                type: string
                format: text
                description: "Error message"
    ServerBusy:
      description: "503: Server busy, please try again later"
      content:
        text/plain:
          schema:
                type: string
                format: text
                description: "Error message"
security:
  - bearerAuth: []         # use the same name as above

#https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml
#https://editor-next.swagger.io/
